#!/usr/bin/env bash

if [ "$BLOCK_BUTTON" = "3" ]; then
    i3-msg -q exec "alacritty --title pacupdate -e sh -c \"yay && read -rsn1 -p 'Done. Press any key to exit.' || read -rsn1 -p 'Error. Press any key to exit.'\""
fi

if [ "$BLOCK_BUTTON" = "1" ]; then
    dunstify -t 0 -r 16000 -i aptdaemon-upgrade "loading AUR package updates" "..."
fi

updatecount=$(yay -Qua | wc -l)
updates=$(yay -Qua | cut -d" " -f1)

if [ "$BLOCK_BUTTON" = "1" ]; then
    dunstify -t 0 -r 16000 -i aptdaemon-upgrade "$updatecount AUR package updates" "$updates"
fi

echo " $updatecount"

if [ "$updatecount" -gt 5 ]; then
    exit 33;
else
	exit 0;
fi
