#!/usr/bin/env bash

updates=$(checkupdates | cut -d" " -f1)
updatecount=$(checkupdates | wc -l)


if [ "$BLOCK_BUTTON" = "1" ]; then
    notify-send -i aptdaemon-upgrade "$updatecount package updates" "$updates"
fi

if [ "$BLOCK_BUTTON" = "3" ]; then
    i3-msg -q exec "urxvt -name pacupdate -e sh -c \"sudo pacman -Syu && read -rsn1 -p 'Press any key to exit.'\""
fi

echo " $updatecount"

if [ "$updatecount" -gt 40 ]; then
    exit 33;
else
	exit 0;
fi
